// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp0IyD793I7PhIr_mxVbd-wR4pNYXL4oE',
    appId: '1:1089546592497:web:94f1f1206c837112408950',
    messagingSenderId: '1089546592497',
    projectId: 'bandy-suhyeon',
    authDomain: 'bandy-suhyeon.firebaseapp.com',
    storageBucket: 'bandy-suhyeon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPzAvbrD4ioXy2wwqBosQoNKaUEjm5Jo',
    appId: '1:1089546592497:android:1e8646a8e5b123c5408950',
    messagingSenderId: '1089546592497',
    projectId: 'bandy-suhyeon',
    storageBucket: 'bandy-suhyeon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtUkOJ2JJQuXW3FSomWAR4g0GopnSLWqE',
    appId: '1:1089546592497:ios:fa42420182ad4f8c408950',
    messagingSenderId: '1089546592497',
    projectId: 'bandy-suhyeon',
    storageBucket: 'bandy-suhyeon.appspot.com',
    iosBundleId: 'com.example.bandyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp0IyD793I7PhIr_mxVbd-wR4pNYXL4oE',
    appId: '1:1089546592497:web:2bf20138d3b135b9408950',
    messagingSenderId: '1089546592497',
    projectId: 'bandy-suhyeon',
    authDomain: 'bandy-suhyeon.firebaseapp.com',
    storageBucket: 'bandy-suhyeon.appspot.com',
  );

}